CREATE TABLE KIOSK_MENU(
MENU_NAME VARCHAR2(30) PRIMARY KEY,
MENU_PRICE NUMBER NOT NULL,
MENU_TYPE VARCHAR2(20)
);


INSERT INTO KIOSK_MENU VALUES('아메리카노', 3000, '커피');
INSERT INTO KIOSK_MENU VALUES('아이스 아메리카노', 3000, '커피');
INSERT INTO KIOSK_MENU VALUES('카페라떼', 4000, '커피');
INSERT INTO KIOSK_MENU VALUES('아이스 카페라뗴', 4000, '커피');
INSERT INTO KIOSK_MENU VALUES('콜드브루', 4500, '커피');


INSERT INTO KIOSK_MENU VALUES('블루베리에이드', 5000, '논커피');
INSERT INTO KIOSK_MENU VALUES('레몬에이드', 5000, '논커피');
INSERT INTO KIOSK_MENU VALUES('허브티', 4500, '논커피');
INSERT INTO KIOSK_MENU VALUES('디카페인커피', 4000, '논커피');


INSERT INTO KIOSK_MENU VALUES('초코케이크', 5000, '디저트');
INSERT INTO KIOSK_MENU VALUES('샌드위치', 5000, '디저트');

INSERT INTO KIOSK_MENU VALUES('샷 추가', 500, '기타');
INSERT INTO KIOSK_MENU VALUES('휘핑크림 추가', 500, '기타');
INSERT INTO KIOSK_MENU VALUES('텀블러 할인', -500, '기타');







SELECT * FROM KIOSK_MENU;


